### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by CodeSearcher59** [nythepegasus/SideJITServer#100]
The install command finally decided to work for me, however the following error message comes up when I try to check the version of the program:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\reida\Documents\Applications\SideJITServer\SideJITServer-1.3.1\venv\Scripts\SideJITServer.exe\__main__.py", line 4, in <module>
  File "C:\Users\reida\Documents\Applications\SideJITServer\SideJITServer-1.3.1\venv\Lib\site-packages\SideJITServer\__init__.py", line 14, in <module>
    from pymobiledevice3.lockdown import LockdownClient, create_using_usbmux
  File "C:\Users\reida\Documents\Applications\SideJITServer\SideJITServer-1.3.1\venv\Lib\site-packages\pymobiledevice3\lockdown.py", line 16, in <module>
    from cryptography.hazmat.primitives import hashes
  File "C:\Users\reida\Documents\Applications\SideJITServer\SideJITServer-1.3.1\venv\Lib\site-packages\cryptography\hazmat\primitives\hashes.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ModuleNotFoundError: No module named '_cffi_backend'

Anyone else having this problem?

**Comment by nythepegasus** [comment]
Could you try the newer version in a fresh venv?
