### ISSUE TITLE
I can't pair my phone on Fedora Linux no matter what I do

### ISSUE THREAD

**Issue by 0hStormy** [nythepegasus/SideJITServer#102]
I tried updating pymobiledevice3, unplugging and re-plugging my phone, tried using venv and the pypi version.

Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:00008110-001559EA0C46801E VERSION:17.5.1 TYPE:iPhone14,5 PAIRED:True>]
Traceback (most recent call last):
  File "/home/stormy/.local/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stormy/.local/lib/python3.12/site-packages/SideJITServer/__init__.py", line 236, in start_server
    dev.pair()
  File "/home/stormy/.local/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 67, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/stormy/.local/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 372, in pair
    self.save_pair_record()
  File "/home/stormy/.local/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 644, in save_pair_record
    client.save_pair_record(self.identifier, self.service.mux_device.devid, record_data)
  File "/home/stormy/.local/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 373, in save_pair_record
    self._send_receive({'MessageType': 'SavePairRecord',
  File "/home/stormy/.local/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 402, in _send_receive
    raise self._raise_mux_exception(response['Number'], f'got an error message: {response}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stormy/.local/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 242, in _raise_mux_exception
    raise exception(message)
pymobiledevice3.exceptions.BadDevError: got an error message: {'MessageType': 'Result', 'Number': 2}

**Comment by KennLDN** [comment]
I am experiencing this exact problem also.

**Comment by nythepegasus** [comment]
Which device and iOS version? Do other pairing methods work like jitterbugpair/pymobiledevice3 directly?

**Comment by 0hStormy** [comment]
I can pair with jitterbugpair

**Comment by 0hStormy** [comment]
Update: I'm using the newest packaged .bin version and it's still having the same issue

**Comment by mrchilliballs** [comment]
exact same error on fedora with the binary and by compiling it

**Comment by pauljako** [comment]
Same issue on NixOS
