### ISSUE TITLE
`{"ERROR": "Could not find device!"}`

### ISSUE THREAD

**Issue by nythepegasus** [nythepegasus/SideJITServer#111]

**Comment by Breh12345** [comment]
Seems like updating does not work

**Comment by Wojdi** [comment]
ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-usbmux-00001111-000A1100A11101A-USB: Traceback (most recent call last):
  File "D:\Programy\SideJITServer-1.3.5\venv\lib\site-packages\pymobiledevice3\tunneld.py", line 199, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\Programy\SideJITServer-1.3.5\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1018, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\Programy\SideJITServer-1.3.5\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 932, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "D:\Programy\SideJITServer-1.3.5\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 298, in start_tunnel
    super().start_tunnel(address, mtu)
  File "D:\Programy\SideJITServer-1.3.5\venv\lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 179, in start_tunnel
    self.tun = TunTapDevice()
  File "D:\Programy\SideJITServer-1.3.5\venv\lib\site-packages\pytun_pmd3\wintun.py", line 222, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

**Comment by ThatKoza** [comment]
im on the newest version, this issue still exists

**Comment by Erisfiregamer1** [comment]
Issue still exists on iOS 17.0.3 iPhone 12

**Comment by Foodie947** [comment]
iOS 17.5.1, i had altserver running on my pc, and for some reason, disabling it worked for me. it might have something to do with two servers attempting to interface with the same device.

**Comment by lewiwiii** [comment]
issue exists on A13, 17.1.2

**Comment by 10XS** [comment]
a14ios17.3上同样有这个问题

**Comment by 10XS** [comment]
![Uploading IMG_5857.jpeg…]()

**Comment by 10XS** [comment]
![Uploading IMG_5849.jpeg…]()

**Comment by 10XS** [comment]
这是个非常巨大的bug，涉及的范围很广，貌似是ios17的一些子版本就会出现{"ERROR": "Could not find any device!"}的问题，希望作者尽快修复；This is a very huge bug, involving a wide range. It seems that some sub-versions of ios17 will appear {"ERROR": "Could not find any device!"} I hope the author can fix the problem as soon as possible.
