### ISSUE TITLE
Cannot start SideJITServer. Ended with multiple exceptions.

### ISSUE THREAD

**Issue by js-john** [nythepegasus/SideJITServer#116]
```
(venv) js@Johns-MacBook-Pro bin % sudo SideJITServer
INFO:     Started server process [45027]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:63924 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 162, in query_personalization_manifest
    return response['ImageSignature']
           ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'ImageSignature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 208, in mount
    manifest = self.query_personalization_manifest('DeveloperDiskImage', hashlib.sha384(image).digest())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 164, in query_personalization_manifest
    raise MissingManifestError()
pymobiledevice3.exceptions.MissingManifestError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/js/bin/SideJITServer/venv/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 252, in start_server
    refresh_devs()
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 124, in refresh_devs
    asyncio.run(auto_mount_personalized(dev))
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 355, in auto_mount_personalized
    await PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 211, in mount
    manifest = await self.get_manifest_from_tss(plistlib.loads(build_manifest.read_bytes()))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/js/bin/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 242, in get_manifest_from_tss
    raise NoSuchBuildIdentityError(f'Could not find the manifest for board {board_id} and chip {chip_id}')
pymobiledevice3.exceptions.NoSuchBuildIdentityError: Could not find the manifest for board 8 and chip 32800
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [45027]
```

**Other info may help**
Python 3.12.3
macOS Sonoma 14.6.1
```
(venv) js@Johns-MacBook-Pro bin % SideJITServer --version
pymobiledevice3: 4.11.20
SideJITServer: 1.3.3
```

**Comment by DanielDavis05** [comment]
Having the same issue, still waiting on it but I believe updating MacOS then Xcode will fix it

**Comment by DanielDavis05** [comment]
> Having the same issue, still waiting on it but I believe updating MacOS then Xcode will fix it

This worked for me, I upgraded to Xcode 16 beta, not sure if that mattered but my MacOS was outdated
