### ISSUE TITLE
Pairing ends with error on Ubuntu 24.04 LTS (privileged/root) CT

### ISSUE THREAD

**Issue by jorycz** [nythepegasus/SideJITServer#134]
I start up privileged (root inside CT is same uid 0 as root on host) container with Ubuntu 24.04 LTS on latest proxmox host 8.2.4.

Added Passthrough iPad (USB device) to CT. Here is **lsusb** from inside of CT:
```
root@jit:~# lsusb 
...
Bus 001 Device 006: ID 05ac:12ab Apple, Inc. iPad
...
```
Install usbmuxd and SideJITServer:

```
git clone ... && cd SideJITServer
python3 -m venv venv
source venv/bin/activate
(venv) root@jit:~/SideJITServer# pip3 install -r requirements.txt
(venv) root@jit:~/SideJITServer# pip3 install SideJITServer
(venv) root@jit:~/SideJITServer# SideJITServer --version
pymobiledevice3: 4.13.10
SideJITServer: 1.3.5
```

So far so good. But I get following error when trying to pair iPad.
```
(venv) root@jit:~/SideJITServer# SideJITServer --pair

Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:UDID-DELETED-FOR-BUG-REPORT VERSION:17.6.1 TYPE:iPad8,3 PAIRED:True>]
Traceback (most recent call last):
  File "/root/SideJITServer/venv/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 246, in start_server
    dev.pair()
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 67, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 378, in pair
    self.save_pair_record()
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 646, in save_pair_record
    client.save_pair_record(self.identifier, self.service.mux_device.devid, record_data)
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 373, in save_pair_record
    self._send_receive({'MessageType': 'SavePairRecord',
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 402, in _send_receive
    raise self._raise_mux_exception(response['Number'], f'got an error message: {response}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 242, in _raise_mux_exception
    raise exception(message)
pymobiledevice3.exceptions.BadDevError: got an error message: {'MessageType': 'Result', 'Number': 2}
```
Communication with iPad is somehow working.

- **Trust this computer** is now **shown** on iPad and I can confirm it using my passcode, but SideJITServer --pair ends with the same error when I try it again.

- **.pymobiledevice3/UDID.plist** is created but not **Xcode_iOS_DDI_Personalized** folder.

Is there anything I can do about it?

**Comment by mrchilliballs** [comment]
Same error on Fedora, compiling both ways + using the linux binary.

**Comment by 7ROBE** [comment]
same error

**Comment by ma-r-s** [comment]
same error

**Comment by just-for-death** [comment]
Any solutions

**Comment by Lolmc0587** [comment]
same here
