### ISSUE TITLE
Wireless JIT trough SideStore not working

### ISSUE THREAD

**Issue by usr577** [nythepegasus/SideJITServer#137]
In SideStore there is the option to enable JIT with SideJITServer wirelessly, which works like a charm from my windows laptop, but doesn't want to work on my Raspberry Pi after many retrys.
I already tried changing the pairing file from SideStore to one generated on my PI, tried the version of SideJITServer that I used on my Laptop(I used 1.3.3 on my Laptop which worked and so far tried 1.3.3 and 1.3.6 on my Pi both not working), the log always looks like this(I manually stopped it after one unsuccessful try):
```shell
pi@raspberrypi:~ $ sudo SideJITServer
INFO:     Started server process [888]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:58488 - "GET / HTTP/1.1" 200 OK
Registration of service SideJITServer._http._tcp.local. in progress...
Service SideJITServer._http._tcp.local. registered
Server started on http://192.168.178.59:8080
192.168.178.32 - - [17/Sep/2024 21:08:59] "GET /UDID/net.kdt.pojavlauncher.PURFJX4AUP HTTP/1.1" 404 -
^CServer stopped.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [888]
Exception ignored in atexit callback: <bound method Zeroconf.unregister_service of <zeroconf._core.Zeroconf object at 0x7fb75dcb50>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_core.py", line 455, in unregister_service
    run_coro_with_timeout(
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked:
/usr/lib/python3.11/asyncio/base_events.py:678: RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
``` 
but on my laptop it says 200 as response code and works, what could be the problem here?(Fyi the errors also appear on my laptop but don't seem to do any harm so i just ignore them)

**Comment by usr577** [comment]
It just magically fixed itself with a reinstall
