### ISSUE TITLE
ubuntu error

### ISSUE THREAD

**Issue by 7ROBE** [nythepegasus/SideJITServer#138]
(venv) lap@lap:~/SideJITServer$ SideJITServer -y -v
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:000xxxxxxxxxxxxxxxxxx VERSION:18.0 TYPE:iPhone14,5 PAIRED:True>]
Traceback (most recent call last):
  File "/home/lap/SideJITServer/venv/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 260, in start_server
    dev.pair()
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 67, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 378, in pair
    self.save_pair_record()
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/lockdown.py", line 646, in save_pair_record
    client.save_pair_record(self.identifier, self.service.mux_device.devid, record_data)
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 373, in save_pair_record
    self._send_receive({'MessageType': 'SavePairRecord',
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 402, in _send_receive
    raise self._raise_mux_exception(response['Number'], f'got an error message: {response}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lap/SideJITServer/venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 242, in _raise_mux_exception
    raise exception(message)
pymobiledevice3.exceptions.BadDevError: got an error message: {'MessageType': 'Result', 'Number': 2}

**Comment by be4ryllium** [comment]
exact same issue here on linux mint

**Comment by just-for-death** [comment]
Any fixes
