### ISSUE TITLE
can't use side jit server it says  failed to create adapter

### ISSUE THREAD

**Issue by TheRealAssassin1St** [nythepegasus/SideJITServer#140]
ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-usbmux-00008130-001661E101F2001C-USB: Traceback (most recent call last):
  File "C:\WINDOWS\system32\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 200, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WINDOWS\system32\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1020, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WINDOWS\system32\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 934, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "C:\WINDOWS\system32\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 298, in start_tunnel
    super().start_tunnel(address, mtu)
  File "C:\WINDOWS\system32\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 179, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "C:\WINDOWS\system32\venv\Lib\site-packages\pytun_pmd3\wintun.py", line 222, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

**Comment by Foodie947** [comment]
same issue

**Comment by gallantcrusader** [comment]
Are you on 18/18.1?

**Comment by Moodoesfunnyhack** [comment]
yes im on 18

**Comment by Moodoesfunnyhack** [comment]
i have the same issue

**Comment by wynwxst** [comment]
This has been solved by downgrading python 3.13-3.12 -> 3.11

**Comment by MikeCoder96** [comment]
You must run the shell (Powershell, CMD, Terminal) as Administrator cause otherwise Python is not able to create the TAP.
I'm using Python 3.11.7

**Comment by lonewolfe92** [comment]
I’m having the same problem and am using power shell as admin with python 3.11. Just one roadblock after another. Makes me regret upgrading my iOS to 17
