### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by Moodoesfunnyhack** [nythepegasus/SideJITServer#148]
when i selected the app it gave an unexpected network error

Exception occurred during processing of request from ('192.168.1.143', 64469)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "C:\Windows\System32\venv\Lib\site-packages\SideJITServer\__init__.py", line 176, in do_GET
    result = device.enable_jit(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\venv\Lib\site-packages\SideJITServer\__init__.py", line 88, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('192.168.1.143', 64470)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "C:\Windows\System32\venv\Lib\site-packages\SideJITServer\__init__.py", line 176, in do_GET
    result = device.enable_jit(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\venv\Lib\site-packages\SideJITServer\__init__.py", line 88, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('192.168.1.143', 64471)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "C:\Windows\System32\venv\Lib\site-packages\SideJITServer\__init__.py", line 176, in do_GET
    result = device.enable_jit(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\venv\Lib\site-packages\SideJITServer\__init__.py", line 88, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy

**Comment by eduardopy** [comment]
I get the exact same error on ios 18.0.1, not sure if its looking for a file that isnt there or what.

**Comment by eduardopy** [comment]
File "C:\Users\a\Documents\jit2\venv\Lib\site-packages\SideJITServer\__init__.py", line 88, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\Documents\jit2\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
----------------------------------------
