### ISSUE TITLE
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by ataraxia-admail** [nythepegasus/SideJITServer#156]
Windows 11, ipadOS 18.0.1
Hi, i was following the setup guide buti was unable to pair with my device. I know that this maybe a duplicate of [Issue#66](https://github.com/nythepegasus/SideJITServer/issues/66) where i also tried the solution given there that was running on Administrator and Wifi, disabling my vpn but it still didn't work for me. I hope that someone could help me with this.

![image](https://github.com/user-attachments/assets/45ab4915-314c-4c33-b928-a01524691b91)
(venv) PS D:\Programs\SideJITServer-1.3.6> SideJITServer --pair
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:00008132-001A381C1185001C VERSION:18.0.1 TYPE:iPad16,3 PAIRED:True>]
Continue? [y/N]: y
INFO:     Started server process [9020]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:63775 - "GET / HTTP/1.1" 200 OK
Registration of service SideJITServer._http._tcp.local. in progress...
Service SideJITServer._http._tcp.local. registered
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Programs\SideJITServer-1.3.6\venv\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
    sys.exit(start_server())
             ~~~~~~~~~~~~^^
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\SideJITServer\__init__.py", line 278, in start_server
    server = HTTPServer(('0.0.0.0', port), SimpleHTTPRequestHandler)
  File "C:\Program Files\Python313\Lib\socketserver.py", line 457, in __init__
    self.server_bind()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\Python313\Lib\http\server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Program Files\Python313\Lib\socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
Exception ignored in atexit callback <bound method Zeroconf.unregister_service of <zeroconf._core.Zeroconf object at 0x000001C790FA1400>>:
Traceback (most recent call last):
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\zeroconf\_core.py", line 455, in unregister_service
    run_coro_with_timeout(
  File "D:\Programs\SideJITServer-1.3.6\venv\Lib\site-packages\zeroconf\_utils\asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked:

**Comment by ataraxia-admail** [comment]
Found the solution, i ran SideJITServer --pair -p 5000 instead of SideJITServer --pair.

**Explained and solved by ChatGPT-4o, i have no idea how this works but i tried and it works anyways since no one answered** 

Replace 5000 with a port number that is less likely to be occupied or restricted (e.g., something like 5000, 8080, 6000, etc.).
This should start the SideJITServer on the specified port, potentially avoiding the permission conflict with the previously attempted port. If this resolves the issue, it indicates that the original port (49151) was either in use or restricted by another process or setting.
