### ISSUE TITLE
SideJITServer startup fail (something with usbmux.py)

### ISSUE THREAD

**Issue by jaezudev** [nythepegasus/SideJITServer#173]
See title. I can't get it to work after I installed it via `pip3 install SideJITServer`. Trying to run it on an amd64 Debian 12 instance with Python 3.11.2 inside of a virtualenv, with all the packages installed correctly.

I should note though that I plan to make this work remotely, hence it running on a remote server (KVM to be specific). If any other info is needed, I'll happily provide it

Log:
```
nis@serbia:~/jit# venv/bin/SideJITServer -y
Attempting to pair to a device! (Ctrl+C to stop)
Traceback (most recent call last):
  File "/root/jit/venv/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/SideJITServer/__init__.py", line 247, in start_server
    devices = select_devices_by_connection_type(connection_type='USB')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 452, in select_devices_by_connection_type
    for device in list_devices(usbmux_address=usbmux_address):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 414, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 410, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 174, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 167, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jit/venv/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 111, in __init__
    self.sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by jaezudev** [comment]
Fixed it by disabling usbmuxd. Might be worth mentioning this conflict somewhere in the docs.

**Comment by jaezudev** [comment]
Never mind, I got it wrong. Usbmuxd HAS to be started for it to function at all
