### ISSUE TITLE
RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited

### ISSUE THREAD

**Issue by takov751** [nythepegasus/SideJITServer#25]
After too many restarts the server crashes with

```
Registration of service SideJITServer._http._tcp.local. in progress...
Traceback (most recent call last):
  File "/usr/local/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/SideJITServer/__init__.py", line 253, in start_server
    create_service()
  File "/usr/local/lib/python3.12/site-packages/SideJITServer/__init__.py", line 202, in create_service
    zeroconf.register_service(service_info)
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_core.py", line 318, in register_service
    run_coro_with_timeout(
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 113, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 97, in await_awaitable
    task = await aw
           ^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_core.py", line 348, in async_register_service
    await self.async_check_service(info, allow_name_change, cooperating_responders, strict)
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_core.py", line 531, in async_check_service
    raise NonUniqueNameException
zeroconf._exceptions.NonUniqueNameException
Exception ignored in atexit callback: <bound method Zeroconf.unregister_service of <zeroconf._core.Zeroconf object at 0x7f972fc170>>
Traceback (most recent call last):
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_core.py", line 455, in unregister_service
    run_coro_with_timeout(
  File "/root/.local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked: 

sys:1: RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

**Comment by stossy11** [comment]
Thats my fault pull request here https://github.com/nythepegasus/SideJITServer/pull/24 I hope nythepegasus accepts it soon

**Comment by takov751** [comment]
Oh, all is well then thanks for the contribution 😀👍

**Comment by OctoNezd** [comment]
Hi! I have same issue

How did you solve it?

I am running app in docker with custom dockerfile that is just pip install SideJITServer and get this:

```
tunnel  | DEBUG:asyncio:Using selector: EpollSelector
tunnel  | Registration of service SideJITServer._http._tcp.local. in progress...
tunnel  | Traceback (most recent call last):
tunnel  |   File "/usr/local/bin/SideJITServer", line 8, in <module>
tunnel  |     sys.exit(start_server())
tunnel  |              ^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
tunnel  |     return self.main(*args, **kwargs)
tunnel  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
tunnel  |     rv = self.invoke(ctx)
tunnel  |          ^^^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
tunnel  |     return ctx.invoke(self.callback, **ctx.params)
tunnel  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
tunnel  |     return __callback(*args, **kwargs)
tunnel  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/site-packages/SideJITServer/__init__.py", line 253, in start_server
tunnel  |     create_service()
tunnel  |   File "/usr/local/lib/python3.12/site-packages/SideJITServer/__init__.py", line 202, in create_service
tunnel  |     zeroconf.register_service(service_info)
tunnel  |   File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 318, in register_service
tunnel  |     run_coro_with_timeout(
tunnel  |   File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 113, in run_coro_with_timeout
tunnel  |     return asyncio.run_coroutine_threadsafe(aw, loop).result(
tunnel  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
tunnel  |     return self.__get_result()
tunnel  |            ^^^^^^^^^^^^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
tunnel  |     raise self._exception
tunnel  |   File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 97, in await_awaitable
tunnel  |     task = await aw
tunnel  |            ^^^^^^^^
tunnel  |   File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 348, in async_register_service
tunnel  |     await self.async_check_service(info, allow_name_change, cooperating_responders, strict)
tunnel  |   File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 531, in async_check_service
tunnel  |     raise NonUniqueNameException
tunnel  | zeroconf._exceptions.NonUniqueNameException
```
