### ISSUE TITLE
Couldn't run SideJITServer

### ISSUE THREAD

**Issue by Rylazius** [nythepegasus/SideJITServer#30]
qwerty@local:~/AltServer $ SideJITServer
Traceback (most recent call last):
  File "/home/qwerty/.local/bin/SideJITServer", line 5, in <module>
    from SideJITServer.__main__ import start_server
  File "/home/qwerty/.local/lib/python3.11/site-packages/SideJITServer/__init__.py", line 19, in <module>
    from pymobiledevice3.tunneld import get_tunneld_devices, TUNNELD_DEFAULT_ADDRESS, TunneldRunner
  File "/home/qwerty/.local/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 27, in <module>
    from pymobiledevice3.remote.tunnel_service import CoreDeviceTunnelProxy, RemotePairingProtocol, TunnelResult, \
  File "/home/qwerty/.local/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 37, in <module>
    from pytun_pmd3 import TunTapDevice
  File "/home/qwerty/.local/lib/python3.11/site-packages/pytun_pmd3/__init__.py", line 6, in <module>
    from pytun_pmd3_c import TunTapDevice
ModuleNotFoundError: No module named 'pytun_pmd3_c'
qwerty@local:~/AltServer $

Raspberry Pi 4
Debian 12

**Comment by nythepegasus** [comment]
Try using the current latest version, also make sure you're running as sudo
