### ISSUE TITLE
No such service: com.apple.internal.dt.remote.debugproxy

### ISSUE THREAD

**Issue by cootshk** [nythepegasus/SideJITServer#31]
Running the shortcut gives me an "Internal server error!" with the following error:
```
2024-04-26 19:03:28 ******.local SideJITServer[3579] ERROR Exception on /******-**********/DolphiniOS/ [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/SideJITServer/__init__.py", line 169, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/SideJITServer/__init__.py", line 81, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
```

**Comment by cootshk** [comment]
going to http://localhost:8080/re/ doesnt fix it either

**Comment by WesleyBryie** [comment]
Try restarting your computer.

Wesley Bryie

***@***.***
***@***.***

https://wesbryie.com/
________________________________

**Comment by dmcpacks** [comment]
Hi, just had the same issue and restarting my Mac didn't fix it. @cootshk did you ever fix it?

INFO:werkzeug:192.168.87.175 - - [22/May/2024 22:20:04] "GET /00008030-00054D2902DA202E/ HTTP/1.1" 200 -
ERROR:SideJITServer:Exception on /00008030-00054D2902DA202E/Sudachi/ [GET]
Traceback (most recent call last):
  File "/Users/user/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/venv/lib/python3.11/site-packages/SideJITServer/__init__.py", line 169, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/venv/lib/python3.11/site-packages/SideJITServer/__init__.py", line 81, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/venv/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
INFO:werkzeug:192.168.87.175 - - [22/May/2024 22:20:06] "GET /00008030-00054D2902DA202E/Sudachi/ HTTP/1.1" 500 -

**Comment by cootshk** [comment]
I created a virtual environment then restarted both my Mac and my phone @dmcpacks

**Comment by fish4terrisa-MSDSM** [comment]
Also faced it today, found it useful to simply restart the computer and ipad.....Don't know why...

**Comment by nythepegasus** [comment]
Try using the current latest version

**Comment by George-Bryant** [comment]
### 我的为什么这样，why？？？？？`INFO:     Started server process [13552]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:65051 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\SideJITServer\__init__.py", line 259, in start_server
    refresh_devs()
  File "C:\Program Files\Python312\Lib\site-packages\SideJITServer\__init__.py", line 123, in refresh_devs
    for dev in get_tunneld_devices():
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38269\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\tunneld.py", line 470, in get_tunneld_devices
    return get_asyncio_loop().run_until_complete(async_get_tunneld_devices(tunneld_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\38269\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\tunneld.py", line 465, in async_get_tunneld_devices
    return await _create_rsds_from_tunnels(tunnels)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\38269\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\tunneld.py", line 504, in _create_rsds_from_tunnels
    await rsd.connect()
  File "C:\Users\38269\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 59, in connect
    await self.service.connect()
  File "C:\Users\38269\AppData\Roaming\Python\Python312\site-packages\pymobiledevice3\remote\remotexpc.py", line 54, in connect
    self._reader, self._writer = await asyncio.open_connection(self.address[0], self.address[1])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python312\Lib\asyncio\proactor_events.py", line 729, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\windows_events.py", line 803, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
OSError: [WinError 1231] 不能访问网络位置。有关网络排除故障的信息，请参阅 Windows 帮助。`
