### ISSUE TITLE
Failed to pair on Windows 11

### ISSUE THREAD

**Issue by 5ur3z** [nythepegasus/SideJITServer#38]
PS C:\Users\Admin> SideJITServer -y
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:xxxxxxxxxxxxxxx VERSION:17.0 TYPE:iPad13,4 PAIRED:True>]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\SideJITServer\__init__.py", line 236, in start_server
    dev.pair()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\lockdown.py", line 60, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\lockdown.py", line 361, in pair
    self.save_pair_record()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\lockdown.py", line 632, in save_pair_record
    client.save_pair_record(self.identifier, self.service.mux_device.devid, record_data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\usbmux.py", line 373, in save_pair_record
    self._send_receive({'MessageType': 'SavePairRecord',
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\usbmux.py", line 402, in _send_receive
    raise self._raise_mux_exception(response['Number'], f'got an error message: {response}')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\usbmux.py", line 242, in _raise_mux_exception
    raise exception(message)
pymobiledevice3.exceptions.MuxException: got an error message: {'MessageType': 'Result', 'Number': 22}

**Comment by nythepegasus** [comment]
Try using the current latest version, also, make sure your device is unlocked and has a password.
