### ISSUE TITLE
Failed to create adapter

### ISSUE THREAD

**Issue by justandree** [nythepegasus/SideJITServer#43]
Intstalled SideJITServer yesterday and it was working like a charm, I retried today just to see all of this cmd red lines of code:

2024-05-15 19:00:36 PC-di-Andrea pymobiledevice3.tunneld[14008] ERROR got exception from start-tunnel-task-usbmux-00008027-0009204C34F8402E-USB: Traceback (most recent call last):
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\tunneld.py", line 168, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 994, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 908, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in start_tunnel
    super().start_tunnel(address, mtu)
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "C:\Users\andyb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

I tried to connect to the 2 ips and they both report this: {"ERROR":"Could not find any device!"}

**Comment by takov751** [comment]
Tunnel couldnt be created are you running the script as administrator?

**Comment by justandree** [comment]
I just used PowerShell instead and it worked out just fine

**Comment by takov751** [comment]
That's great news. Please could you close this issue as solved. Much appreciated
