### ISSUE TITLE
error when enabling jit using sidestore + sidejitserver

### ISSUE THREAD

**Issue by melikootje** [nythepegasus/SideJITServer#47]
i get the following error when trying to enable JIT on my pc that runs both sidestore and sidejitserver

````
ERROR:SideJITServer:Exception on /00008130-001615C82612001C/PojavLauncher/ [GET]
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\SideJITServer\__init__.py", line 169, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\SideJITServer\__init__.py", line 81, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
INFO:werkzeug:192.168.1.32 - - [20/May/2024 19:59:24] "GET /00008130-001615C82612001C/PojavLauncher/ HTTP/1.1" 500 
```-`

**Comment by melikootje** [comment]
Yes i did

**Comment by TheTechGuy2** [comment]
same problem here

**Comment by nythepegasus** [comment]
Try using the current latest version, also make sure you're running as admin
