### ISSUE TITLE
Device Locked Error

### ISSUE THREAD

**Issue by kuj000** [nythepegasus/SideJITServer#68]
Installed and ran SideJITServer for the first time last night with minimal issues. Today, when I attempted to run SideJITServer again, I repeatedly got this error when attempting to execute. This error shows even when the device is unlocked. 

My initial thought was that maybe there was an issue with dynamic IP being enabled on my router, but I might be offbase here. Any help is appreciated!!!

Pairing will still attempt when I run the `--pair` command, and the "Trust this device?" prompt will show up on my iPad, however the following is what I get once I select "y" to continue:

```INFO:     Started server process [57724]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
INFO:     127.0.0.1:50306 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\SideJITServer\__init__.py", line 251, in start_server
    refresh_devs()
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\SideJITServer\__init__.py", line 123, in refresh_devs
    auto_mount_personalized(dev)
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 355, in auto_mount_personalized
    PersonalizedImageMounter(lockdown=lockdown).mount(image, build_manifest, trustcache)
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 213, in mount
    self.upload_image(self.IMAGE_TYPE, image, manifest)
  File "C:\Users\arrrr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\mobile_image_mounter.py", line 115, in upload_image
    raise PyMobileDevice3Exception(f'command ReceiveBytes failed with: {result}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: command ReceiveBytes failed with: {'Error': 'DeviceLocked'}

**Comment by nythepegasus** [comment]
Ensure your device is unlocked.

**Comment by theveloperspl** [comment]
> Ensure your device is unlocked.

I managed to run is successfully, JIT was enabled, shortcut worked but now every attempt ends with this error.
iPad is unlocked, "Trust" button is clicked, password entered.
What may be the case here?
