### ISSUE TITLE
No route to host when using Zerotier

### ISSUE THREAD

**Issue by Jonathan0827** [nythepegasus/SideJITServer#74]
Environment
- iPhone 13 with iOS 17.4 RC installed
- M2 MBA with macOS Sequoia DB1 installed
- Used ZeroTier One to connect my Mac without being on the same network
- `pymobiledevice3: 4.2.3` `SideJITServer: 1.3.1` `Python 3.12.4`
Log
```python
Traceback (most recent call last):
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 169, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 76, in enable_jit
    if app.pid > 0 and app.pid == self.launch_app(app.bundle):
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 64, in launch_app
    with DvtSecureSocketProxyService(lockdown=self.handle) as dvt:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/pymobiledevice3/services/dvt/dvt_secure_socket_proxy.py", line 24, in __init__
    super().__init__(lockdown, service_name, remove_ssl_context=remove_ssl_context)
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/pymobiledevice3/services/remote_server.py", line 362, in __init__
    super().__init__(lockdown, service_name, is_developer_service=is_developer_service)
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 90, in start_lockdown_developer_service
    return self.start_lockdown_service_without_checkin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 66, in start_lockdown_service_without_checkin
    return ServiceConnection.create_using_tcp(self.service.address[0], self.get_service_port(name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlim/Downloads/SideJITServer-1.3.1/venv/lib/python3.12/site-packages/pymobiledevice3/service_connection.py", line 81, in create_using_tcp
    sock = socket.create_connection((hostname, port))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host
```

**Comment by nythepegasus** [comment]
I do not think VPNs are supported. See my response in #94
