### ISSUE TITLE
No such service

### ISSUE THREAD

**Issue by matei1413** [nythepegasus/SideJITServer#75]
When i run SideJIT shortcut, i get this error:
`ERROR:SideJITServer:Exception on /00008020-000E54C222BB002E/PojavLauncher/ [GET]
Traceback (most recent call last):
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 169, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 81, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\Documents\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
INFO:werkzeug:172.20.10.5 - - [23/Jun/2024 22:27:15] "GET /00008020-000E54C222BB002E/PojavLauncher/ HTTP/1.1" 500 -`
^^^
What i saw on the PowerShell window

On the iphone i got a notification with internal server error

**My device:**
iPhone XS
iOS 17.5.1

**Comment by matei1413** [comment]
Fixed it, i had to bring up the JIT prompt in the app i wanted (Pojav Launcher) and then run the script.
