### ISSUE TITLE
DeprecationWarning: There is no current event loop

### ISSUE THREAD

**Issue by lienting885** [nythepegasus/SideJITServer#76]
**iPhone12**
**iOS17.5.1**
**Windows10 22H2**
**Pymobiledevice3 4.2.3**
**Python 3.12**
**SideJitServer 1.3.1**

When I run sidejitser --pair, it gives me an error:
```
(venv) PS C:\Users\Administrator\Desktop\SideJITServer> SideJITServer --pair
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:XXXXXXXX-XXXXXXXXXXXXXXXX VERSION:17.5.1 TYPE:iPhone13,2 PAIRED:True>]
Continue? [y/N]: y
INFO:     Started server process [XXXX]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 251, in start_server
    refresh_devs()
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 121, in refresh_devs
    for dev in get_tunneld_devices():
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 426, in get_tunneld_devices
    return get_asyncio_loop().run_until_complete(async_get_tunneld_devices(tunneld_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 407, in async_get_tunneld_devices
    tunnels = resp.json()
              ^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SideJITServer\venv\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(venv) PS C:\Users\Administrator\Desktop\SideJITServer>
```

**Comment by bucyumaaaaaa** [comment]
I'm also getting this bug and updating my pymobiledevice3 version doesn't fix it either.

**Comment by tristafae** [comment]
Try run with

`sudo SideJITServer`

Instead
Worked for me!

**Comment by s-leeq** [comment]
> Try run with
> 
> `sudo SideJITServer`
> 
> Instead of SideJITServer --pair Worked for me! This was on Mac is it the same for windows?

No luck for me:( 
Using macOS 12.7.5, Python 3.12.4

**Comment by nythepegasus** [comment]
Should be fixed on latest versions
