### ISSUE TITLE
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy

### ISSUE THREAD

**Issue by Duy-Thanh** [nythepegasus/SideJITServer#77]
I have followed these instructions, I have iOS 17.0.3 running on iPhone 11. When I try to enable JIT, I see this error:

```
INFO:werkzeug:192.168.30.101 - - [30/Jun/2024 07:20:37] "GET /00008030-000D79EA21D3C02E/UTM/ HTTP/1.1" 500 -
INFO:werkzeug:192.168.30.101 - - [30/Jun/2024 07:20:47] "GET /00008030-000D79EA21D3C02E/ HTTP/1.1" 200 -
INFO:werkzeug:192.168.30.101 - - [30/Jun/2024 07:20:50] "GET /00008030-000D79EA21D3C02E/LiveContainer HTTP/1.1" 308 -
ERROR:SideJITServer:Exception on /00008030-000D79EA21D3C02E/LiveContainer/ [GET]
Traceback (most recent call last):
  File "F:\SideJITServer\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SideJITServer\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SideJITServer\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SideJITServer\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 169, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 81, in enable_jit
    self.handle.service.address[0], self.handle.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy
```

**Comment by lienting885** [comment]
[https://github.com/nythepegasus/SideJITServer/issues/31](url)

**Comment by lienting885** [comment]
https://github.com/nythepegasus/SideJITServer/issues/31
