### ISSUE TITLE
Continuously getting error: pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter.

### ISSUE THREAD

**Issue by WillamSun** [nythepegasus/SideJITServer#80]
I am connecting an iPhone 14 Pro Max with iOS 18.0 Beta 2 to Windows 11 with pymobiledevice3: 4.2.3 and SideJITServer: 1.3.1. I ran `SideJITServer --pair` and eventually got this:
```
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:00008120-0001715A0A90201E VERSION:18.0 TYPE:iPhone15,3 PAIRED:True>]
Continue? [y/N]: y
INFO:     Started server process [29940]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-usbmux-00008120-0001715A0A90201E-USB: Traceback (most recent call last):
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 168, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 994, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 908, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in start_tunnel
    super().start_tunnel(address, mtu)
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-usbmux-00008120-0001715A0A90201E-USB: Traceback (most recent call last):
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 168, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 994, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 908, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in start_tunnel
    super().start_tunnel(address, mtu)
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
  File "D:\G\git\SideJITServer\venv\Lib\site-packages\pytun_pmd3\wintun.py", line 206, in __init__
    raise PyWinTunException(f"Failed to create adapter. Last error: {last_error.value}")
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0
```
The error occurs every 3 seconds. How do i do?

**Comment by WillamSun** [comment]
> I don't think it works on ios 18

do we have any other ways to enable jit on iOS 18?

**Comment by WillamSun** [comment]
I’ve been heard and seen people using sidejitserver to enable jit on iOS 18 and I think it also works for me but something just mis-configured

**Comment by ItzHenry1** [comment]
@WillamSun @THENOGOD 

I discovered how to fix this error, I just ran PowerShell/CMD as Administrator atleast on Windows machine, If you are using Linux distro or MacOS try running with `sudo SideJITServer` connect your device and run the shortcuts script.

I suggest you run SideJITServer --pair with sudo too

**Comment by WillamSun** [comment]
@ItzHenry1
Thanks very much! Works for me
