### ISSUE TITLE
SideJITServer --pair does not work

### ISSUE THREAD

**Issue by Landon-Kuehner** [nythepegasus/SideJITServer#82]
```
[root@archlinux sideJit]# SideJITServer --pair
Attempting to pair to a device! (Ctrl+C to stop)
Traceback (most recent call last):
  File "/home/landonk/Downloads/sideJit/.venv/bin/SideJITServer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/SideJITServer/__init__.py", line 223, in start_server
    devices = select_devices_by_connection_type(connection_type='USB')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 448, in select_devices_by_connection_type
    for device in list_devices(usbmux_address=usbmux_address):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 410, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 406, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 174, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 167, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/landonk/Downloads/sideJit/.venv/lib/python3.12/site-packages/pymobiledevice3/usbmux.py", line 111, in __init__
    self.sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

pymobiledevice3: 4.2.3
SideJITServer: 1.3.1

**Comment by Xenonus** [comment]
You have to download usbmuxd and start the daemon

**Comment by Landon-Kuehner** [comment]
> You have to download usbmuxd and start the daemon

I have installed usbmuxd and enabled it in systemd, and I no longer get errors, but it still isn't detecting me plugging in my phone

**Comment by tristafae** [comment]
Try running

`sudo SideJITServer`

Instead of SideJITServer --pair
Worked on my Mac!

**Comment by Landon-Kuehner** [comment]
I am still getting the same exact errors

**Comment by gino0210** [comment]
i know its a month later but i had the same exact issue. it may seem like alot but i went to sideloadly.io to download sideloadly and the requirements are that you have to download itunes and icloud but from the links they provide and once i installed both itunes and icloud restarted my pc and then enabled wifi connection (when you open itunes and sync your phone if you go to your device in itunes you will see the option to enable wifi something) and the it seemed to fix the problem.

**Comment by Landon-Kuehner** [comment]
> i know its a month later but i had the same exact issue. it may seem like alot but i went to sideloadly.io to download sideloadly and the requirements are that you have to download itunes and icloud but from the links they provide and once i installed both itunes and icloud restarted my pc and then enabled wifi connection (when you open itunes and sync your phone if you go to your device in itunes you will see the option to enable wifi something) and the it seemed to fix the problem.

You can't do that on linux.

**Comment by nythepegasus** [comment]
This worked on my Mac, will have to test Linux/Windows
