### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by KusanagiShiro** [nythepegasus/SideJITServer#83]
I am running into issues with the shortcut. I followed every guide, and every single thing is supposedly right. Here is a log of my last attempt.

(venv) C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\SideJITServer>SideJITServer.exe
INFO:     Started server process [26552]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
INFO:     127.0.0.1:57818 - "GET / HTTP/1.1" 200 OK
Registration of service SideJITServer._http._tcp.local. in progress...
Service SideJITServer._http._tcp.local. registered
 * Serving Flask app 'SideJITServer'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.0.2:8080
INFO:werkzeug:Press CTRL+C to quit
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [26552]
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\SideJITServer\__init__.py", line 172, in start_tunneld_proc
    TunneldRunner.create(TUNNELD_DEFAULT_ADDRESS[0], TUNNELD_DEFAULT_ADDRESS[1],
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 283, in create
    usbmux_monitor=usbmux_monitor)._run_app()
                                   ^^^^^^^^^^
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 399, in _run_app
    uvicorn.run(self._app, host=self.host, port=self.port, loop='asyncio')
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
WARNING:zeroconf:Error with socket 1516 (('169.254.181.64', 5353))): [WinError 59] An unexpected network error occurred
Traceback (most recent call last):
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 523, in _loop_writing
    fut.result()
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 803, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gail's Computer\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 462, in finish_socket_func
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 59] An unexpected network error occurred
Exception ignored in atexit callback: <bound method Zeroconf.unregister_service of <zeroconf._core.Zeroconf object at 0x0000025281954F80>>
Traceback (most recent call last):
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\zeroconf\_core.py", line 455, in unregister_service
    run_coro_with_timeout(
  File "C:\SideJITServer-main\SideJITServer\venv\Lib\site-packages\zeroconf\_utils\asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked:
sys:1: RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by nythepegasus** [comment]
Could you try the latest version? Also ensure your firewall is off and you are putting the correct URL in
