### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nevespt** [nythepegasus/SideJITServer#88]
2024-07-19 07:14:01 DESKTOP-EM5UTDL SideJITServer[6824] ERROR Exception on /00008130-00026CD400FA8D3A/Provenance/ [GET]
Traceback (most recent call last):
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\SideJITServer\__init__.py", line 168, in enable_jit_for_app
    return dev.enable_jit(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\SideJITServer\__init__.py", line 82, in enable_jit
    app.pid = self.launch_app(app.bundle, True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\SideJITServer\__init__.py", line 63, in launch_app
    with DvtSecureSocketProxyService(lockdown=self.handle) as dvt:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\services\dvt\dvt_secure_socket_proxy.py", line 24, in __init__
    super().__init__(lockdown, service_name, remove_ssl_context=remove_ssl_context)
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\services\remote_server.py", line 362, in __init__
    super().__init__(lockdown, service_name, is_developer_service=is_developer_service)
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\services\lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 90, in start_lockdown_developer_service
    return self.start_lockdown_service_without_checkin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 66, in start_lockdown_service_without_checkin
    return ServiceConnection.create_using_tcp(self.service.address[0], self.get_service_port(name))
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')

**Comment by DELOLCAT** [comment]
i got the same thing

**Comment by nythepegasus** [comment]
Could you try using the latest version?
