### ISSUE TITLE
Unknown error python when running pairing

### ISSUE THREAD

**Issue by EnderRobber101** [nythepegasus/SideJITServer#95]
`Traceback (most recent call last):
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 168, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 994, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 908, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 295, in start_tunnel
    super().start_tunnel(address, mtu)
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
pytun.Error: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/utils.py", line 44, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 188, in start_tunnel_task
    logger.debug(f'got {e.__class__.__name__} from tunnel --rsd {tun.address} {tun.port}')
                                                                 ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'address'
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='start-tunnel-task-usbmux-00008112-00040466115A201E-USB' coro=<TunneldCore.start_tunnel_task() done, defined at /home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/utils.py:41> exception=AttributeError("'NoneType' object has no attribute 'address'")>
Traceback (most recent call last):
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 168, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 994, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 908, in start_tcp_tunnel
    tunnel.start_tunnel(handshake_response['clientParameters']['address'],
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 295, in start_tunnel
    super().start_tunnel(address, mtu)
  File "/home/ryanpi/Documents/SideJITServer/venv/lib/python3.11/site-packages/pymobiledevice3/remote/tunnel_service.py", line 177, in start_tunnel
    self.tun = TunTapDevice()
               ^^^^^^^^^^^^^^
`

this is the error i get from when i run `SideJITServer --pair`  

everything else works perfectly

**Comment by theJayTea** [comment]
i got the same error!

**Comment by nythepegasus** [comment]
Could you try the latest version? It works on my Mac, I haven't tried Linux/Windows recently yet.
