### ISSUE TITLE
RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited

### ISSUE THREAD

**Issue by yummy1gay** [nythepegasus/SideJITServer#97]
Registration of service SideJITServer._http._tcp.local. in progress...
Service SideJITServer._http._tcp.local. registered
 * Serving Flask app 'SideJITServer'
 * Debug mode: off
Сделана попытка доступа к сокету методом, запрещенным правами доступа
Exception ignored in atexit callback: <bound method Zeroconf.unregister_service of <zeroconf._core.Zeroconf object at 0x00000275A5D5C7D0>>
Traceback (most recent call last):
  File "C:\Users\artem\AppData\Local\Programs\Python\Python311\Lib\site-packages\zeroconf\_core.py", line 455, in unregister_service
    run_coro_with_timeout(
  File "C:\Users\artem\AppData\Local\Programs\Python\Python311\Lib\site-packages\zeroconf\_utils\asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked:
sys:1: RuntimeWarning: coroutine 'Zeroconf.async_unregister_service' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

How to fix it?

**Comment by yummy1gay** [comment]
need to change the port, add to the command for example --port 9731
